### ISSUE TITLE
Implement hook_config_info()

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/api#4]
This module doesn't seem to implement `hook_config_info()`, though it includes a few config files.

**Comment by ghost** [comment]
I think this is the reason for this error:

> Configuration sync failed. The following errors were reported:
The configuration "api.settings" is not owned by any module. Try enabling the module that provides this configuration, then importing again.

**Comment by ghost** [comment]
Here's a PR: https://github.com/backdrop-contrib/api/pull/5

**Comment by klonos** [comment]
Thanks @BWPanda 👍
